### ISSUE TITLE
Documentation examples don't work

### ISSUE THREAD

**Issue by sdlumpp** [nhcb/entsog-py#6]
Package installed and example code run in environment. The following error message is output:

C:\Users\XXXXX\PycharmProjects\entsog-test\venv\Scripts\python.exe C:/Users/XXXXX/PycharmProjects/entsog-test/main.py
Traceback (most recent call last):
  File "C:/Users/XXXXX/PycharmProjects/entsog-test/main.py", line 10, in <module>
    client.query_connection_points()
  File "C:\Users\XXXXX\PycharmProjects\entsog-test\venv\lib\site-packages\entsog\entsog.py", line 180, in query_connection_points
    response = self._base_request(endpoint='/connectionpoints')
  File "C:\Users\XXXXX\PycharmProjects\entsog-test\venv\lib\site-packages\entsog\decorators.py", line 22, in retry_wrapper
    result = func(*args, **kwargs)
TypeError: _base_request() missing 1 required positional argument: 'params'

**Comment by nhcb** [comment]
Thanks for letting me know about the error. I released a new version with the fixes (and also working examples). Again, thanks for letting me know.

**Comment by sdlumpp** [comment]
v0.9.0 seems to work fine. Thanks for the quick response.
